pln = input("Plural Noun: ")
adj = input("Adjective: ")
spl = input("Same Plural Noun: ")
ani = input("Animal: ")
nou = input("Noun: ")
adj2 = input("Adjective: ")
adj3 = input("Adjective: ")
pln2 = input("Plural Noun: ")
nou2 = input("Noun: ")
adj4 = input("Adjective: ")
nou3 = input("Noun: ")
nou4 = input("Noun: ")
adj5 = input("Adjective: ")
nou5 = input("Noun: ")
pln3 = input("Plural Noun: ")
adj6 = input("Adjective: ")
nou6 = input("Noun: ")

madlib = f"This is how I made one million {pln} in the stock market. It's simple. At the present time, any {adj} investor with a little capital should be able to double his {spl} in a few months. All the experts agree that we are nearing the end of the {ani} market. Just recently, for instance, the American {nou} and Foundry Company has shown a/an {adj2} trend. Conditions indicate a/an {adj3} market for their principal product, automatic {pln2}. Internation Telephone and {nou2} Company also looks {adj4}. At the end of the last fiscal {nou3}, they were earning ten dollars a/an {nou4}. Another {adj5} tip is Consolidated {nou5}. This outfit manufactures and sells electronic {pln3} of a very {adj6} quality. But whatever you do, act now. Remeber, prospertiy is just around the {nou6}."
print(madlib)
